project:
  type: website

website:
  title: "ONS Visual Journalism"
  navbar:
    search: false
    left:
      - whoarewe.qmd
      - recent.qmd
      - resources.qmd
      - cotm.qmd
      - visualvocabulary.qmd
      - library.qmd
  favicon: logo.png

format:
  html:
    page-layout: full
    anchor-sections: false
    link-external-newwindow: true
    theme:
      - cosmo
      - ONSstyle.scss
    toc: false

filters:
  - carousel    
