project:
  type: website

website:
  title: "ONS Visual Journalism"
  body-header: _includes/header.html
  navbar:
    search: false
    background: none
    left:
      - whoarewe.qmd
      - recent.qmd
      - resources.qmd
      - cotm.qmd
      - visualvocabulary.qmd
      - library.qmd
  favicon: logo.png

format:
  html:
    page-layout: full
    anchor-sections: false
    link-external-newwindow: true
    theme:
      - ONSstyle.scss
      - cosmo
    toc: false
    css:
      - https://cdn.ons.gov.uk/sdc/design-system/73.3.0/css/main.css
      - https://cdn.ons.gov.uk/vendor/accessible-autocomplete/3.0.1/accessible-autocomplete.min.css


filters:
  - carousel    
