name: build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up R
        uses: r-lib/actions/setup-r@465b7d8e732ca3921382b1674c59bada9cbf3399 # v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libuv1-dev


      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("jsonlite", "curl", "dplyr", "glue", "stringr", "DT", "rmarkdown", "knitr", "readr", "lubridate", "tidyr"), repos="https://cloud.r-project.org")'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@8a96df13519ee81fd526f2dfca5962811136661b # v2

      - name: Run carousel generation script
        run: |
          Rscript scripts/cotm_carousel.R

      - name: Render site
        run: |
          quarto render

      - name: Deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@8a96df13519ee81fd526f2dfca5962811136661b # v2
        with:
          target: gh-pages
